{{- if and (not .Values.auth.existingSecret) .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoscaler.tokenSecretName" . }}
  labels:
    {{- include "autoscaler.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.auth.token | quote }}
{{- end }}
